### ISSUE TITLE
Extension Asks Me to Install It

### ISSUE THREAD

**Issue by ToddlerNaruto** [meganz/firefox-web-extension#1]
Hi, I seem to be experiencing a glitch where MEGA keeps asking me to install the extension, even though it's already installed and I am actively using it.

I logged into https://mega.nz first, then installed the Firefox extension, and finally logged into https://mega.nz via the extension like I always used to do with the older legacy version.

Any help at all with resolving this issue would be highly appreciated.

**Comment by cr-nz** [comment]
Can you please paste a screenshot here when it happens again?

**Comment by ToddlerNaruto** [comment]
I'll be able to post a screenshot soon @cr-nz , waiting for my bandwith to be maxed out near midnight.

(the messages only pops up when I queue a big batch of files for download)

**Comment by ToddlerNaruto** [comment]
@cr-nz Here's the screenshot, sorry for the delay.

[img]https://i.imgur.com/kOEmDxH.png[/img]

**Comment by ToddlerNaruto** [comment]
@cr-nz Here's the screenshot, sorry for the delay.

![megafirefoxextensionerror](https://user-images.githubusercontent.com/32668273/31504239-b8e5bc18-af26-11e7-9409-40b09575a9f4.PNG)

**Comment by cr-nz** [comment]
Now I know what you mean. I think we have a fix coming for that soon.
