### ISSUE TITLE
Default Download Folder Option Missing

### ISSUE THREAD

**Issue by ToddlerNaruto** [meganz/firefox-web-extension#2]
Hi, ever since the extension switched over to web extension, this feature vanished.

Was it done on purpose, or just a mistake? I'd prefer having it back please.

**Comment by cr-nz** [comment]
Unfortunately there are limited options for downloading files with Firefox's new WebExtensions format. Our legacy extension suddenly stopped working properly in Firefox 56 and would have been completely unsupported in Firefox 57 anyway. The only option was to upgrade to the new format.

In the `about:preferences` page of Firefox you can still change the download location:
![image](https://user-images.githubusercontent.com/9664533/31421470-e5e32d0e-ae1d-11e7-8002-931f38f1e797.png)

If you really still prefer the legacy extension which is more configurable, you can download it from:
https://eu.static.mega.co.nz/3/meganz-legacy-v3.16.1.xpi

It will only work properly in Firefox version <= 55 and is no longer supported. It may also work in the [Pale Moon](https://www.palemoon.org/) browser which is a fork of Firefox that will not remove the support for legacy extensions. I haven't tested this though.

**Comment by ToddlerNaruto** [comment]
I guess it'll have to do for now until Firefox improves their new webextensions format.
