### ISSUE TITLE
MEGA File Size Error

### ISSUE THREAD

**Issue by ToddlerNaruto** [meganz/firefox-web-extension#3]
@cr-nz I think this is related to MEGA not realizing I'm using the Firefox extension, but I've been getting errors whenever I try to download files over 2GB.

![megafileerror](https://user-images.githubusercontent.com/32668273/31601808-f40f2b30-b20f-11e7-9aee-b702fcbf5b45.PNG)

**Comment by cr-nz** [comment]
I think the Firefox WebExtension can only handle files of less than 1GB in size reliably. The API support in Firefox for downloading large files is not yet available. The legacy extension could handle larger files as it had access to different APIs but those are not available for WebExtensions. The other option for downloading large files is installing [MegaSync](https://github.com/meganz/MEGAsync).

**Comment by ToddlerNaruto** [comment]
@cr-nz Update: Now it won't even let me download 800+ MB files, keeps insisting I use the desktop app.

Can this be fixed?

**Comment by ianamk** [comment]
I;d say install PaleMoon or downgrade to Firefox-esr and use the old addon (if you can find it)
works great under PaleMoon for me no file size limits no Firefox crashes (I had crashes in FF 56 and 57 with the new addon)

**Comment by cr-nz** [comment]
That's unfortunately about the maximum that can be downloaded reliably with the new Web Extension format. You can also download the desktop app (MEGAsync) which allows faster downloads and bigger files. Or alternatively, try the legacy addon:

https://eu.static.mega.co.nz/3/meganz-legacy-v3.16.1.xpi
