### ISSUE TITLE
can we get a link/fork of the old  xpi addon

### ISSUE THREAD

**Issue by ianamk** [meganz/firefox-web-extension#4]
the new webext addon is horrible I know this is a firefox issue blocking addons from acceding local disk but can we get a link/update for the old non-webext addon for Firefox-esr and PaleMoon users 
all I can say is the webext addon crashes Firefox when downloading "big" files I've migrated to PaleMoon for MEGA use and I don't have that issue but it's a good thing I had a local copy of the old xpi or else I couldn't install the addon as mega.nz only has the incompatible webext xpi addon :(

**Comment by cr-nz** [comment]
Here's a link to the last legacy Firefox extension release:
https://eu.static.mega.co.nz/3/meganz-legacy-v3.16.1.xpi

**Comment by cr-nz** [comment]
The legacy Firefox extension for Pale Moon can now be found at:
http://mega.nz/meganz-legacy.xpi.

To install it you need to save it to your local disk and then drag it into the browser and then it should install. Then visit https://mega.nz and it should load. The extension will be updated with future web client releases (usually weekly). It may notify you about updates in the extension if it is open and you'll need to re-download and install it manually again.
